image: python:3.10-alpine

stages:
  - build_deploy
  
variables:
  PACKAGE_INDEX: https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi



run_build_deploy:
  stage: build_deploy
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev  "
      when: never
    - when: always
  before_script:
    - echo "Installing dependencies"
    - python -m pip install -U pip
    - pip install pipenv
    - pipenv requirements --exclude-markers --dev > requirements.txt
    - pip install -r requirements.txt
  script:
    - echo "Building $CI_PROJECT_NAME"
    - python -m build
    - echo "Deploying $CI_PROJECT_NAME to $PACKAGE_INDEX"
    - twine upload dist/* -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD --repository-url $PACKAGE_INDEX
  after_script:
    - echo "$CI_PROJECT_NAME deployed successfully"
  # cache:
  #   key: "$CI_COMMIT_REF_NAME"
  #   paths:
  #     - /app/folder
  #   policy: pull-push
    # policy: pull
