# Form implementation generated from reading ui file 'd:\Development\Projects\qtmvvmtoolkit\tests\pages\templates\PageUser.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_PageUser(object):
    def setupUi(self, PageUser):
        PageUser.setObjectName("PageUser")
        PageUser.resize(721, 347)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(PageUser)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=PageUser)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.entryName = QtWidgets.QLineEdit(parent=PageUser)
        self.entryName.setObjectName("entryName")
        self.gridLayout.addWidget(self.entryName, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=PageUser)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinAge = QtWidgets.QSpinBox(parent=PageUser)
        self.spinAge.setObjectName("spinAge")
        self.gridLayout.addWidget(self.spinAge, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=PageUser)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonDisplay = QtWidgets.QPushButton(parent=PageUser)
        self.buttonDisplay.setObjectName("buttonDisplay")
        self.horizontalLayout.addWidget(self.buttonDisplay)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(
            343,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem3)

        self.retranslateUi(PageUser)
        QtCore.QMetaObject.connectSlotsByName(PageUser)

    def retranslateUi(self, PageUser):
        _translate = QtCore.QCoreApplication.translate
        PageUser.setWindowTitle(_translate("PageUser", "Form"))
        self.label_3.setText(_translate("PageUser", "User"))
        self.label.setText(_translate("PageUser", "Name"))
        self.label_2.setText(_translate("PageUser", "Age"))
        self.buttonDisplay.setText(_translate("PageUser", "Display User"))
