# Form implementation generated from reading ui file 'd:\source\projects\PyQtMvvm\qt-mvvm\qtmvvmkit\templates\pages\NavigationPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PageNavifation(object):
    def setupUi(self, PageNavifation):
        PageNavifation.setObjectName("PageNavifation")
        PageNavifation.resize(917, 448)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageNavifation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(PageNavifation)
        self.frame.setMinimumSize(QtCore.QSize(250, 300))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.topNavigationBar = QtWidgets.QVBoxLayout()
        self.topNavigationBar.setObjectName("topNavigationBar")
        self.verticalLayout_4.addLayout(self.topNavigationBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.bottomNavigationBar = QtWidgets.QVBoxLayout()
        self.bottomNavigationBar.setObjectName("bottomNavigationBar")
        self.verticalLayout_3.addLayout(self.bottomNavigationBar)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addWidget(self.frame)
        self.navigationOutlet = QtWidgets.QStackedWidget(PageNavifation)
        self.navigationOutlet.setMinimumSize(QtCore.QSize(0, 300))
        self.navigationOutlet.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.navigationOutlet.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.navigationOutlet.setObjectName("navigationOutlet")
        self.horizontalLayout.addWidget(self.navigationOutlet)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PageNavifation)
        QtCore.QMetaObject.connectSlotsByName(PageNavifation)

    def retranslateUi(self, PageNavifation):
        _translate = QtCore.QCoreApplication.translate
        PageNavifation.setWindowTitle(_translate("PageNavifation", "Form"))
