services:
  qtmvvmtoolkit:
    image: qtmvvmtoolkit
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
      target: dev
    command: sleep infinity
    network_mode: host
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ..:/workspaces/qtmvvmtoolkit:cached
